apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  generation: 5
  name: k8s-consul-registrar
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-consul-registrar
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-consul-registrar
    spec:
      containers:
      - args:
        - agent
        - -datacenter=$(REGISTER_CONSULCENTER)
        - -client=0.0.0.0
        - -bind=0.0.0.0
        - -join=$(REGISTER_CONSULADDRESS)
        env:
        - name: REGISTER_CONSULADDRESS
          value: 10.210.48.53
        - name: REGISTER_CONSULCENTER
          value: dc1
        image: registry-itwork.yonghui.cn/library/consul:1.7.3
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8500
          timeoutSeconds: 10
        name: consul-agent
        ports:
        - containerPort: 8500
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8500
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: CLUSTER_NAME
          value: idc-thanos
        - name: MODE
          value: registrar
        - name: CONSUL_ADDRESS
          value: 127.0.0.1:8500
        - name: SYNC_PERIOD
          value: "60"
        - name: SHARD_PATHS
          value: shard-1,shard-2,shard-3,shard-4,shard-5,shard-6,shard-7,shard-8,shard-9,shard-10,shard-11,shard-12,shard-13,shard-14,shard-15,shard-16,shard-17,shard-18,shard-19,shard-20,shard-21
        image: registry-itwork.yonghui.cn/base/testmetrics:v12
        imagePullPolicy: Always
        name: k8s-consul-registrar-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: k8s-consul-registrar-sa
      serviceAccountName: k8s-consul-registrar-sa
      terminationGracePeriodSeconds: 30


